# Projeto Fifa

### Aqui será feito a limpeza e alguns testesde um banco de dados puxado do Kaggle com dados do jogo fifa

In [44]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [45]:
base = pd.read_csv(r'C:\Users\danii\OneDrive - UNIP\Documents\bkp\ESTUDOS\Projeto.fifa\fifa_cleaned.csv')

In [46]:
base

,id,name,full_name,birth_date,age,height_cm,weight_kgs,positions,nationality,overall_rating,...,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB
0,158023,L. Messi,Lionel Andrés Messi Cuccittini,1987-06-24,31,170.18,72.1,"CF,RW,ST",Argentina,94,...,64+2,61+2,61+2,61+2,64+2,59+2,48+2,48+2,48+2,59+2
1,190460,C. Eriksen,Christian Dannemann Eriksen,1992-02-14,27,154.94,76.2,"CAM,RM,CM",Denmark,88,...,71+3,71+3,71+3,71+3,71+3,66+3,57+3,57+3,57+3,66+3
2,195864,P. Pogba,Paul Pogba,1993-03-15,25,190.50,83.9,"CM,CAM",France,88,...,76+3,77+3,77+3,77+3,76+3,74+3,72+3,72+3,72+3,74+3
3,198219,L. Insigne,Lorenzo Insigne,1991-06-04,27,162.56,59.0,"LW,ST",Italy,88,...,63+3,58+3,58+3,58+3,63+3,58+3,44+3,44+3,44+3,58+3
4,201024,K. Koulibaly,Kalidou Koulibaly,1991-06-20,27,187.96,88.9,CB,Senegal,88,...,73+3,77+3,77+3,77+3,73+3,76+3,85+3,85+3,85+3,76+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17949,204322,R. McKenzie,Rory McKenzie,1993-10-07,25,175.26,74.8,"RM,CAM,CM",Scotland,67,...,53+2,52+2,52+2,52+2,53+2,50+2,46+2,46+2,46+2,50+2
17950,239762,M. Sipľak,Michal Sipľak,1996-02-02,23,182.88,79.8,LB,Slovakia,59,...,57+2,55+2,55+2,55+2,57+2,57+2,58+2,58+2,58+2,57+2
17951,235155,J. Bekkema,Jan Bekkema,1996-04-09,22,185.42,89.8,GK,Netherlands,59,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17952,244883,A. Al Yami,Abdulrahman Al Yami,1997-06-19,21,175.26,64.9,"ST,LM",Saudi Arabia,59,...,41+2,35+2,35+2,35+2,41+2,39+2,32+2,32+2,32+2,39+2
17953,247187,Júnior Brumado,José Francisco dos Santos Júnior,1999-05-15,19,190.50,79.8,ST,Brazil,59,...,41+2,40+2,40+2,40+2,41+2,40+2,40+2,40+2,40+2,40+2

In [47]:
base[['frist_name', 'middle_name']]=base['full_name'].str.split(' ', expand=True,n = 1)

In [48]:
base

,id,name,full_name,birth_date,age,height_cm,weight_kgs,positions,nationality,overall_rating,...,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,frist_name,middle_name
0,158023,L. Messi,Lionel Andrés Messi Cuccittini,1987-06-24,31,170.18,72.1,"CF,RW,ST",Argentina,94,...,61+2,61+2,64+2,59+2,48+2,48+2,48+2,59+2,Lionel,Andrés Messi Cuccittini
1,190460,C. Eriksen,Christian Dannemann Eriksen,1992-02-14,27,154.94,76.2,"CAM,RM,CM",Denmark,88,...,71+3,71+3,71+3,66+3,57+3,57+3,57+3,66+3,Christian,Dannemann Eriksen
2,195864,P. Pogba,Paul Pogba,1993-03-15,25,190.50,83.9,"CM,CAM",France,88,...,77+3,77+3,76+3,74+3,72+3,72+3,72+3,74+3,Paul,Pogba
3,198219,L. Insigne,Lorenzo Insigne,1991-06-04,27,162.56,59.0,"LW,ST",Italy,88,...,58+3,58+3,63+3,58+3,44+3,44+3,44+3,58+3,Lorenzo,Insigne
4,201024,K. Koulibaly,Kalidou Koulibaly,1991-06-20,27,187.96,88.9,CB,Senegal,88,...,77+3,77+3,73+3,76+3,85+3,85+3,85+3,76+3,Kalidou,Koulibaly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17949,204322,R. McKenzie,Rory McKenzie,1993-10-07,25,175.26,74.8,"RM,CAM,CM",Scotland,67,...,52+2,52+2,53+2,50+2,46+2,46+2,46+2,50+2,Rory,McKenzie
17950,239762,M. Sipľak,Michal Sipľak,1996-02-02,23,182.88,79.8,LB,Slovakia,59,...,55+2,55+2,57+2,57+2,58+2,58+2,58+2,57+2,Michal,Sipľak
17951,235155,J. Bekkema,Jan Bekkema,1996-04-09,22,185.42,89.8,GK,Netherlands,59,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jan,Bekkema
17952,244883,A. Al Yami,Abdulrahman Al Yami,1997-06-19,21,175.26,64.9,"ST,LM",Saudi Arabia,59,...,35+2,35+2,41+2,39+2,32+2,32+2,32+2,39+2,Abdulrahman,Al Yami
17953,247187,Júnior Brumado,José Francisco dos Santos Júnior,1999-05-15,19,190.50,79.8,ST,Brazil,59,...,40+2,40+2,41+2,40+2,40+2,40+2,40+2,40+2,José,Francisco dos Santos Júnior

In [49]:
base[['last_name', 'middle_name1']]=base['full_name'].str.rsplit(' ', expand=True,n = 1)

In [50]:
base

,id,name,full_name,birth_date,age,height_cm,weight_kgs,positions,nationality,overall_rating,...,RWB,LB,LCB,CB,RCB,RB,frist_name,middle_name,last_name,middle_name1
0,158023,L. Messi,Lionel Andrés Messi Cuccittini,1987-06-24,31,170.18,72.1,"CF,RW,ST",Argentina,94,...,64+2,59+2,48+2,48+2,48+2,59+2,Lionel,Andrés Messi Cuccittini,Lionel Andrés Messi,Cuccittini
1,190460,C. Eriksen,Christian Dannemann Eriksen,1992-02-14,27,154.94,76.2,"CAM,RM,CM",Denmark,88,...,71+3,66+3,57+3,57+3,57+3,66+3,Christian,Dannemann Eriksen,Christian Dannemann,Eriksen
2,195864,P. Pogba,Paul Pogba,1993-03-15,25,190.50,83.9,"CM,CAM",France,88,...,76+3,74+3,72+3,72+3,72+3,74+3,Paul,Pogba,Paul,Pogba
3,198219,L. Insigne,Lorenzo Insigne,1991-06-04,27,162.56,59.0,"LW,ST",Italy,88,...,63+3,58+3,44+3,44+3,44+3,58+3,Lorenzo,Insigne,Lorenzo,Insigne
4,201024,K. Koulibaly,Kalidou Koulibaly,1991-06-20,27,187.96,88.9,CB,Senegal,88,...,73+3,76+3,85+3,85+3,85+3,76+3,Kalidou,Koulibaly,Kalidou,Koulibaly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17949,204322,R. McKenzie,Rory McKenzie,1993-10-07,25,175.26,74.8,"RM,CAM,CM",Scotland,67,...,53+2,50+2,46+2,46+2,46+2,50+2,Rory,McKenzie,Rory,McKenzie
17950,239762,M. Sipľak,Michal Sipľak,1996-02-02,23,182.88,79.8,LB,Slovakia,59,...,57+2,57+2,58+2,58+2,58+2,57+2,Michal,Sipľak,Michal,Sipľak
17951,235155,J. Bekkema,Jan Bekkema,1996-04-09,22,185.42,89.8,GK,Netherlands,59,...,NaN,NaN,NaN,NaN,NaN,NaN,Jan,Bekkema,Jan,Bekkema
17952,244883,A. Al Yami,Abdulrahman Al Yami,1997-06-19,21,175.26,64.9,"ST,LM",Saudi Arabia,59,...,41+2,39+2,32+2,32+2,32+2,39+2,Abdulrahman,Al Yami,Abdulrahman Al,Yami
17953,247187,Júnior Brumado,José Francisco dos Santos Júnior,1999-05-15,19,190.50,79.8,ST,Brazil,59,...,41+2,40+2,40+2,40+2,40+2,40+2,José,Francisco dos Santos Júnior,José Francisco dos Santos,Júnior

In [51]:
base.drop('last_name', axis = 1, inplace = True )

base.drop('middle_name', axis = 1, inplace = True )

base = base.rename(columns={'middle_name1': 'last_name'})

In [52]:
base

,id,name,full_name,birth_date,age,height_cm,weight_kgs,positions,nationality,overall_rating,...,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,frist_name,last_name
0,158023,L. Messi,Lionel Andrés Messi Cuccittini,1987-06-24,31,170.18,72.1,"CF,RW,ST",Argentina,94,...,61+2,61+2,64+2,59+2,48+2,48+2,48+2,59+2,Lionel,Cuccittini
1,190460,C. Eriksen,Christian Dannemann Eriksen,1992-02-14,27,154.94,76.2,"CAM,RM,CM",Denmark,88,...,71+3,71+3,71+3,66+3,57+3,57+3,57+3,66+3,Christian,Eriksen
2,195864,P. Pogba,Paul Pogba,1993-03-15,25,190.50,83.9,"CM,CAM",France,88,...,77+3,77+3,76+3,74+3,72+3,72+3,72+3,74+3,Paul,Pogba
3,198219,L. Insigne,Lorenzo Insigne,1991-06-04,27,162.56,59.0,"LW,ST",Italy,88,...,58+3,58+3,63+3,58+3,44+3,44+3,44+3,58+3,Lorenzo,Insigne
4,201024,K. Koulibaly,Kalidou Koulibaly,1991-06-20,27,187.96,88.9,CB,Senegal,88,...,77+3,77+3,73+3,76+3,85+3,85+3,85+3,76+3,Kalidou,Koulibaly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17949,204322,R. McKenzie,Rory McKenzie,1993-10-07,25,175.26,74.8,"RM,CAM,CM",Scotland,67,...,52+2,52+2,53+2,50+2,46+2,46+2,46+2,50+2,Rory,McKenzie
17950,239762,M. Sipľak,Michal Sipľak,1996-02-02,23,182.88,79.8,LB,Slovakia,59,...,55+2,55+2,57+2,57+2,58+2,58+2,58+2,57+2,Michal,Sipľak
17951,235155,J. Bekkema,Jan Bekkema,1996-04-09,22,185.42,89.8,GK,Netherlands,59,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jan,Bekkema
17952,244883,A. Al Yami,Abdulrahman Al Yami,1997-06-19,21,175.26,64.9,"ST,LM",Saudi Arabia,59,...,35+2,35+2,41+2,39+2,32+2,32+2,32+2,39+2,Abdulrahman,Yami
17953,247187,Júnior Brumado,José Francisco dos Santos Júnior,1999-05-15,19,190.50,79.8,ST,Brazil,59,...,40+2,40+2,41+2,40+2,40+2,40+2,40+2,40+2,José,Júnior

In [53]:
base.dtypes

id             int64
name          object
full_name     object
birth_date    object
age            int64
               ...
CB            object
RCB           object
RB            object
frist_name    object
last_name     object
Length: 94, dtype: object

In [62]:
base['birth_date'] = base['birth_date'].astype('datetime64')

In [66]:
base['birth_date'] = base['birth_date'].dt.strftime('%d/%m/%Y')

AttributeError: Can only use .dt accessor with datetimelike values

In [67]:
base

,id,name,full_name,birth_date,age,height_cm,weight_kgs,positions,nationality,overall_rating,...,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,frist_name,last_name
0,158023,L. Messi,Lionel Andrés Messi Cuccittini,24/06/1987,31,170.18,72.1,"CF,RW,ST",Argentina,94,...,61+2,61+2,64+2,59+2,48+2,48+2,48+2,59+2,Lionel,Cuccittini
1,190460,C. Eriksen,Christian Dannemann Eriksen,14/02/1992,27,154.94,76.2,"CAM,RM,CM",Denmark,88,...,71+3,71+3,71+3,66+3,57+3,57+3,57+3,66+3,Christian,Eriksen
2,195864,P. Pogba,Paul Pogba,15/03/1993,25,190.50,83.9,"CM,CAM",France,88,...,77+3,77+3,76+3,74+3,72+3,72+3,72+3,74+3,Paul,Pogba
3,198219,L. Insigne,Lorenzo Insigne,04/06/1991,27,162.56,59.0,"LW,ST",Italy,88,...,58+3,58+3,63+3,58+3,44+3,44+3,44+3,58+3,Lorenzo,Insigne
4,201024,K. Koulibaly,Kalidou Koulibaly,20/06/1991,27,187.96,88.9,CB,Senegal,88,...,77+3,77+3,73+3,76+3,85+3,85+3,85+3,76+3,Kalidou,Koulibaly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17949,204322,R. McKenzie,Rory McKenzie,07/10/1993,25,175.26,74.8,"RM,CAM,CM",Scotland,67,...,52+2,52+2,53+2,50+2,46+2,46+2,46+2,50+2,Rory,McKenzie
17950,239762,M. Sipľak,Michal Sipľak,02/02/1996,23,182.88,79.8,LB,Slovakia,59,...,55+2,55+2,57+2,57+2,58+2,58+2,58+2,57+2,Michal,Sipľak
17951,235155,J. Bekkema,Jan Bekkema,09/04/1996,22,185.42,89.8,GK,Netherlands,59,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jan,Bekkema
17952,244883,A. Al Yami,Abdulrahman Al Yami,19/06/1997,21,175.26,64.9,"ST,LM",Saudi Arabia,59,...,35+2,35+2,41+2,39+2,32+2,32+2,32+2,39+2,Abdulrahman,Yami
17953,247187,Júnior Brumado,José Francisco dos Santos Júnior,15/05/1999,19,190.50,79.8,ST,Brazil,59,...,40+2,40+2,41+2,40+2,40+2,40+2,40+2,40+2,José,Júnior

In [68]:
base2 = base.dropna()

In [69]:
base2

,id,name,full_name,birth_date,age,height_cm,weight_kgs,positions,nationality,overall_rating,...,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,frist_name,last_name
0,158023,L. Messi,Lionel Andrés Messi Cuccittini,24/06/1987,31,170.18,72.1,"CF,RW,ST",Argentina,94,...,61+2,61+2,64+2,59+2,48+2,48+2,48+2,59+2,Lionel,Cuccittini
1,190460,C. Eriksen,Christian Dannemann Eriksen,14/02/1992,27,154.94,76.2,"CAM,RM,CM",Denmark,88,...,71+3,71+3,71+3,66+3,57+3,57+3,57+3,66+3,Christian,Eriksen
2,195864,P. Pogba,Paul Pogba,15/03/1993,25,190.50,83.9,"CM,CAM",France,88,...,77+3,77+3,76+3,74+3,72+3,72+3,72+3,74+3,Paul,Pogba
3,198219,L. Insigne,Lorenzo Insigne,04/06/1991,27,162.56,59.0,"LW,ST",Italy,88,...,58+3,58+3,63+3,58+3,44+3,44+3,44+3,58+3,Lorenzo,Insigne
5,203376,V. van Dijk,Virgil van Dijk,08/07/1991,27,193.04,92.1,CB,Netherlands,88,...,82+3,82+3,78+3,80+3,86+3,86+3,86+3,80+3,Virgil,Dijk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17938,176580,L. Suárez,Luis Alberto Suárez Díaz,24/01/1987,32,182.88,86.2,ST,Uruguay,91,...,68+5,68+5,69+5,66+5,63+5,63+5,63+5,66+5,Luis,Díaz
17940,183277,E. Hazard,Eden Hazard,07/01/1991,28,172.72,76.2,"LW,CF",Belgium,91,...,63+3,63+3,66+3,60+3,49+3,49+3,49+3,60+3,Eden,Hazard
17941,192985,K. De Bruyne,Kevin De Bruyne,28/06/1991,27,154.94,69.9,"CAM,CM",Belgium,91,...,77+3,77+3,77+3,73+3,66+3,66+3,66+3,73+3,Kevin,Bruyne
17943,190871,Neymar Jr,Neymar da Silva Santos Junior,05/02/1992,27,175.26,68.0,"LW,CAM",Brazil,92,...,60+3,60+3,66+3,61+3,47+3,47+3,47+3,61+3,Neymar,Junior
17944,20801,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,05/02/1985,34,187.96,83.0,"ST,LW",Portugal,94,...,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3,Cristiano,Aveiro

In [94]:
faltantes = base.isnull().sum().sort_values(ascending=False)[:45]

faltantes

national_team             17097
national_jersey_number    17097
national_team_position    17097
national_rating           17097
tags                      16537
traits                     9817
RAM                        2065
LM                         2065
CAM                        2065
RW                         2065
RF                         2065
CF                         2065
LF                         2065
LW                         2065
RS                         2065
ST                         2065
LCM                        2065
CM                         2065
RCM                        2065
RM                         2065
LWB                        2065
LDM                        2065
LS                         2065
CDM                        2065
RDM                        2065
RWB                        2065
LB                         2065
LCB                        2065
CB                         2065
RCB                        2065
RB                         2065
LAM                        2065
club_join_date             1936
release_clause_euro        1837
last_name                   384
contract_end_year           361
value_euro                  255
wage_euro                   246
club_jersey_number           14
club_position                14
club_rating                  14
club_team                    14
penalties                     0
GK_diving                     0
marking                       0
dtype: int64

##### Podemos ver que os dados faltantes são referentes a seleção, posição e clube.
#### Sabendo que nem todos os jogadores vestiram a camisa de suas seleções, nem todos tem uma estimativa para todas as posições
#### e que alguns jogadores ficam sem clube, podemos assumir que esses valores serão zero.

In [106]:
base['national_team'].fillna('Nenhum', inplace = True)
base['national_jersey_number'].fillna('0', inplace = True)
base['national_team_position'].fillna('Nenhuma', inplace = True)
base['national_rating'].fillna('0', inplace = True)
base['tags'].fillna('Nenhuma', inplace = True)
base['traits'].fillna('Nenhuma', inplace = True)

base['RAM'].fillna('0', inplace = True)
base['LM'].fillna('0', inplace = True)
base['CAM'].fillna('0', inplace = True)
base['RW'].fillna('0', inplace = True)
base['RF'].fillna('0', inplace = True)
base['CF'].fillna('0', inplace = True)
base['LF'].fillna('0', inplace = True)
base['LW'].fillna('0', inplace = True)
base['RS'].fillna('0', inplace = True)
base['ST'].fillna('0', inplace = True)
base['LCM'].fillna('0', inplace = True)
base['CM'].fillna('0', inplace = True)
base['RCM'].fillna('0', inplace = True)
base['RM'].fillna('0', inplace = True)
base['LWB'].fillna('0', inplace = True)
base['LDM'].fillna('0', inplace = True)
base['LS'].fillna('0', inplace = True)
base['CDM'].fillna('0', inplace = True)
base['RDM'].fillna('0', inplace = True)
base['RWB'].fillna('0', inplace = True)
base['LB'].fillna('0', inplace = True)
base['LCB'].fillna('0', inplace = True)
base['CB'].fillna('0', inplace = True)
base['RCB'].fillna('0', inplace = True)
base['RB'].fillna('0', inplace = True)
base['LAM'].fillna('0', inplace = True)

base['club_jersey_number'].fillna('0', inplace = True)
base['club_position'].fillna('Nenhuma', inplace = True)
base['club_rating'].fillna('0', inplace = True)
base['club_team'].fillna('Sem clube', inplace = True)


faltantes2 = base.isnull().sum().sort_values(ascending=False)[:10]

faltantes2

club_join_date         1936
release_clause_euro    1837
last_name               384
contract_end_year       361
value_euro              255
wage_euro               246
RB                        0
GK_kicking                0
LW                        0
RS                        0
dtype: int64

#### Agora para os dados faltantes das colunas 'contract_end_year', 'value_euro', 'release_clause_euro' e 'wage_euro' vamos tratar. 
#### Fazendo uma média e preenchendos com esses valores.

In [123]:
base['release_clause_euro'].fillna(base['release_clause_euro'].mean(), inplace = True)
base['value_euro'].fillna(base['value_euro'].mean(), inplace = True)
base['wage_euro'].fillna(base['wage_euro'].mean(), inplace = True)
base['contract_end_year'].fillna(2023, inplace = True)
base['club_join_date'].fillna(2018-1-1, inplace = True)

faltantes3 = base.isnull().sum().sort_values(ascending=False)[:10]

faltantes3

last_name         384
GK_diving           0
RS                  0
ST                  0
LS                  0
traits              0
tags                0
GK_reflexes         0
GK_positioning      0
GK_kicking          0
dtype: int64

#### E para coluna Last_name iremos excluir aqueles que tem esse dado faltante.

In [124]:
base3 = base.dropna()

base3

,id,name,full_name,birth_date,age,height_cm,weight_kgs,positions,nationality,overall_rating,potential,value_euro,wage_euro,preferred_foot,international_reputation(1-5),weak_foot(1-5),skill_moves(1-5),work_rate,body_type,release_clause_euro,club_team,club_rating,club_position,club_jersey_number,club_join_date,contract_end_year,national_team,national_rating,national_team_position,national_jersey_number,crossing,finishing,heading_accuracy,short_passing,volleys,dribbling,curve,freekick_accuracy,long_passing,ball_control,acceleration,sprint_speed,agility,reactions,balance,shot_power,jumping,stamina,strength,long_shots,aggression,interceptions,positioning,vision,penalties,composure,marking,standing_tackle,sliding_tackle,GK_diving,GK_handling,GK_kicking,GK_positioning,GK_reflexes,tags,traits,LS,ST,RS,LW,LF,CF,RF,RW,LAM,CAM,RAM,LM,LCM,CM,RCM,RM,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,frist_name,last_name
0,158023,L. Messi,Lionel Andrés Messi Cuccittini,24/06/1987,31,170.18,72.1,"CF,RW,ST",Argentina,94,94,110500000.0,565000.0,Left,5,4,4,Medium/ Low,Messi,226500000.0,FC Barcelona,86.0,RW,10.0,2004-07-01,2021,Argentina,82.0,RF,10.0,86,95,70,92,86,97,93,94,89,96,91,86,93,95,95,85,68,72,66,94,48,22,94,94,75,96,33,28,26,6,11,15,14,8,"#Dribbler,#Distance Shooter,#Crosser,#FK Speci...","Finesse Shot,Long Shot Taker (CPU AI Only),Spe...",89+2,89+2,89+2,93+2,93+2,93+2,93+2,93+2,93+2,93+2,93+2,91+2,85+2,85+2,85+2,91+2,64+2,61+2,61+2,61+2,64+2,59+2,48+2,48+2,48+2,59+2,Lionel,Cuccittini
1,190460,C. Eriksen,Christian Dannemann Eriksen,14/02/1992,27,154.94,76.2,"CAM,RM,CM",Denmark,88,89,69500000.0,205000.0,Right,3,5,4,High/ Medium,Lean,133800000.0,Tottenham Hotspur,83.0,LCM,23.0,2013-08-30,2020,Denmark,78.0,CAM,10.0,88,81,52,91,80,84,86,87,89,91,76,73,80,88,81,84,50,92,58,89,46,56,84,91,67,88,59,57,22,9,14,7,7,6,"#Playmaker ,#Crosser,#FK Specialist,#Complete...","Flair,Long Shot Taker (CPU AI Only),Playmaker ...",79+3,79+3,79+3,85+3,84+3,84+3,84+3,85+3,86+3,86+3,86+3,86+3,85+3,85+3,85+3,86+3,71+3,71+3,71+3,71+3,71+3,66+3,57+3,57+3,57+3,66+3,Christian,Eriksen
2,195864,P. Pogba,Paul Pogba,15/03/1993,25,190.50,83.9,"CM,CAM",France,88,91,73000000.0,255000.0,Right,4,4,5,High/ Medium,Normal,144200000.0,Manchester United,82.0,LCM,6.0,2016-08-09,2021,France,84.0,RDM,6.0,80,75,75,86,85,87,85,82,90,90,71,79,76,82,66,90,83,88,87,82,78,64,82,88,82,87,63,67,67,5,6,2,4,3,"#Dribbler,#Playmaker ,#Strength,#Complete Mid...","Flair,Long Passer (CPU AI Only),Long Shot Take...",81+3,81+3,81+3,82+3,83+3,83+3,83+3,82+3,84+3,84+3,84+3,83+3,84+3,84+3,84+3,83+3,76+3,77+3,77+3,77+3,76+3,74+3,72+3,72+3,72+3,74+3,Paul,Pogba
3,198219,L. Insigne,Lorenzo Insigne,04/06/1991,27,162.56,59.0,"LW,ST",Italy,88,88,62000000.0,165000.0,Right,3,4,4,High/ Medium,Normal,105400000.0,Napoli,82.0,LS,24.0,2010-07-01,2022,Italy,83.0,LW,10.0,86,77,56,85,74,90,87,77,78,93,94,86,94,83,93,75,53,75,44,84,34,26,83,87,61,83,51,24,22,8,4,14,9,10,"#Speedster,#Dribbler,#Crosser,#Acrobat","Finesse Shot,Long Shot Taker (CPU AI Only),Spe...",78+3,78+3,78+3,86+3,85+3,85+3,85+3,86+3,86+3,86+3,86+3,86+3,78+3,78+3,78+3,86+3,63+3,58+3,58+3,58+3,63+3,58+3,44+3,44+3,44+3,58+3,Lorenzo,Insigne
4,201024,K. Koulibaly,Kalidou Koulibaly,20/06/1991,27,187.96,88.9,CB,Senegal,88,91,60000000.0,135000.0,Right,3,3,2,High/ High,Normal,106500000.0,Napoli,82.0,LCB,26.0,2014-07-01,2021,Nenhum,0,Nenhuma,0,30,22,83,68,14,69,28,28,60,63,70,75,50,82,40,55,81,75,94,15,87,88,24,49,33,80,91,88,87,7,11,7,13,5,"#Tackling ,#Tactician ,#Strength,#Complete Def...",Power Header,53+3,53+3,53+3,53+3,54+3,54+3,54+3,53+3,55+3,55+3,55+3,57+3,61+3,61+3,61+3,57+3,73+3,77+3,77+3,77+3,73+3,76+3,85+3,85+3,85+3,76+3,Kalidou,Koulibaly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17949,204322,R. McKenzie,Rory McKenzie,07/10/1993,25,175.26,74.8,"RM,CAM,CM",Scotland,67,70,975000.0,3000.0,Right,1,3,3,High/ Medium,Normal,1800000.0,Kilmarnock,67.0,SUB,7.0,2010-01-01,2020,Nenhum,0,Nenhuma,0,57,61,60,66,37,64,53,47,61,66,83,86,93,63,82,51,77,75,64,54,69,41,60,64,63,56,40,20,18,15,11,15,12,7,#Acrobat,Nenhuma,62+2,62+2,62+2,66+2,64+2,64+2,64+2,66+2,65+2,65+2,65+2,66+2,60+2,60+2,60+2,66+2,53+2,52+2,52+2,52+2,53+2,50+2,46+2,46+2,46+2,50+2,Rory,McKenzie
17950,239762,M. Sipľak,Michal Sipľak,02/02/1996,23,182.88,79.8,LB,Slovakia,59,67,190000.0,1000.0,Left,1,3,2,Medium/ High,Normal,295000.0,Cracovia,65.0,LB,3.0,2017-07-07,2023,Nenhum,0,Nenhuma,0,50,19,53,55,31,52,26,28,43,53,70,64,54,50,53,27,74,66,70,22,62,55,42,39,32,52,53,64,60,15,7,7,15,8,Nenhuma,Nenhuma,43+2,43+2,43+2,47+2,45+2,45+2,45+2,47+2,46+2,46+2,46+2,50+2,48+2,48+2,48+2,50+2,57+2,55+2,55+2,55+2,57+2,57+2,58+2,58+2,58+2,57+2,Michal,Sipľak
17951,235155,J. Bekkema,Jan Bekkema,09/04/1996,22,185.42,89.8,GK,Netherlands,59,67,170000.0,1000.0,Right,1,1,1,Medium/ Medium,Normal,289000.0,SC Heerenveen,69.0,RES,31.0,2016-07-01,2019,Nenhum,0,Nenhuma,0,11,9,13,26,9,12,13,12,24,18,27,22,29,48,38,17,43,25,63,9,27,10,5,25,16,47,9,12,13,63,57,50,58,63,Nenhuma,Nenhuma,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Jan,Bekkema
17952,244883,A. Al Yami,Abdulrahman Al Yami,19/06/1997,21,175.26,64.9,"ST,LM",Saudi Arabia,59,71,280000.0,4000.0,Right,1,4,3,Medium/ Low,Lean,532000.0,Al Hilal,74.0,RES,87.0,2017-08-12,2020,Nenhum,0,Nenhuma,0,42,60,55,49,49,57,47,39,37,56,84,86,65,53,73,56,58,58,49,58,38,15,54,52,50,53,16,18,17,15,14,12,6,9,Nenhuma,Nenhuma,58+2,58+2,58+2,58+2,58+2,58+2,58+2,58+2,55+2,55+2,55+2,56+2,47+2,47+2,47+2,56+2,41+2,35+2,35+2,35+2,41+2,39+2,32+2,32+2,32+2,39+2,Abdulrahman,Yami
17953,247187,Júnior Brumado,José Francisco dos Santos Júnior,15/05/1999,19,190.50,79.8,ST,Brazil,59,75,325000.0,2000.0,Right,1,4,2,Medium/ Medium,Normal,626000.0,FC Midtjylland,71.0,RES,74.0,2019-01-31,2021,Nenhum,0,Nenhuma,0,32,58,58,47,39,58,35,25,37,56,67,72,71,54,59,61,60,57,67,53,67,20,53,49,52,45,23,31,21,9,14,12,13,14,Nenhuma,Nenhuma,57+2,57+2,57+2,54+2,56+2,56+2,56+2,54+2,54+2,54+2,54+2,52+2,47+2,47+2,47+2,52+2,41+2,40+2,40+2,40+2,41+2,40+2,40+2,40+2,40+2,40+2,José,Júnior

In [126]:
base3.to_csv(r'C:\Users\danii\OneDrive - UNIP\Documents\bkp\ESTUDOS\Projeto.fifa\fifa_cleaned_versaoInicial2.csv')

## Com isso é finalizado a limpeza e os testes nos dados.